name: Validate API swagger documentation

on: push

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: swagger-validator
      uses: mbowman100/swagger-validator-action@master
      with:
        files: $(git ls-files '*.ymal')
        # files: ${{ steps.getfiles.outputs.file_list }} # For if you're using output
